/**
 * GET /api/bible
 *
 * Reads a church-owned/licensed local Bible pack generated by
 * scripts/install-local-bible.mjs. UnoWorship still does not ship licensed
 * Bible text by default.
 */

import fs from 'node:fs';
import path from 'node:path';
import { NextRequest, NextResponse } from 'next/server';
import { formatReference, parseReference } from '@/lib/bible/referenceParser';
import type { BibleBook, BibleBookMeta, BibleData, BibleReference, BibleVerse } from '@/lib/bible/types';
import { dataPath } from '@/lib/localLibraryPath';

const LOCAL_BIBLE_PATH = dataPath('bibles', 'local-bible.json');

let cache: { mtimeMs: number; data: BibleData } | null = null;

function readLocalBible(): BibleData | null {
  if (!fs.existsSync(LOCAL_BIBLE_PATH)) return null;
  const stat = fs.statSync(LOCAL_BIBLE_PATH);
  if (cache && cache.mtimeMs === stat.mtimeMs) return cache.data;
  const parsed = JSON.parse(fs.readFileSync(LOCAL_BIBLE_PATH, 'utf8')) as BibleData;
  cache = {
    mtimeMs: stat.mtimeMs,
    data: parsed,
  };
  return parsed;
}

function toBookMeta(book: BibleBook): BibleBookMeta & { chapters: { num: number; verseCount: number }[] } {
  return {
    num: book.num,
    id: book.id,
    name: book.name,
    abbr: book.abbr,
    testament: book.testament,
    chapterCount: book.chapters.length,
    chapters: book.chapters.map((chapter) => ({
      num: chapter.num,
      verseCount: chapter.verses.length,
    })),
  };
}

function getChapterVerses(data: BibleData, ref: BibleReference): BibleVerse[] {
  const book = data.books.find((item) => item.id === ref.bookId);
  const chapter = book?.chapters.find((item) => item.num === ref.chapter);
  if (!chapter) return [];
  if (ref.verses.length === 0) return chapter.verses;
  const requested = new Set(ref.verses);
  return chapter.verses.filter((verse) => requested.has(verse.num));
}

function parseDirectReference(params: URLSearchParams, books: BibleBookMeta[]): BibleReference | null {
  const bookId = params.get('bookId')?.trim();
  const chapter = Number(params.get('chapter'));
  if (!bookId || !Number.isFinite(chapter) || chapter < 1) return null;

  const book = books.find((item) => item.id === bookId);
  if (!book) return null;

  const start = Number(params.get('start') || params.get('verse') || 0);
  const end = Number(params.get('end') || start || 0);
  const verses: number[] = [];
  if (Number.isFinite(start) && Number.isFinite(end) && start > 0 && end >= start) {
    for (let value = start; value <= end; value += 1) verses.push(value);
  }

  return {
    bookId,
    bookName: book.name,
    chapter,
    verses,
  };
}

function clampVersesPerSection(value: string | null) {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) return 2;
  return Math.min(5, Math.max(1, Math.round(parsed)));
}

/** 개역개정 등의 편집 소제목(<...>)을 절 본문에서 제거한다. 예: "<천지 창조> 태초에…" → "태초에…" */
function stripHeadings(text: string): string {
  return text
    .replace(/<[^>]*>/g, '')
    // 일부 로컬 본문 데이터가 절 범위의 끝 번호를 다음 절 본문 앞에 붙인다(예: "-5 이는...").
    .replace(/^\s*-\d+\s+/, '')
    .replace(/\s{2,}/g, ' ')
    .trim();
}

function buildSections(verses: BibleVerse[], versesPerSection: number) {
  const sections: string[] = [];
  for (let i = 0; i < verses.length; i += versesPerSection) {
    const text = verses
      .slice(i, i + versesPerSection)
      .map((verse) => `${verse.num}. ${stripHeadings(verse.text)}`)
      .join('\n')
      .trim();
    if (text) sections.push(text);
  }
  return sections;
}

export async function GET(request: NextRequest) {
  const data = readLocalBible();
  if (!data) {
    return NextResponse.json(
      {
        error: 'local_bible_not_installed',
        message:
          '설치된 로컬 성경 본문이 없습니다. 교회가 보유하거나 사용 허가를 받은 본문 팩을 data/bibles/local-bible.json 으로 설치해야 합니다.',
      },
      { status: 403 }
    );
  }

  const { searchParams } = new URL(request.url);
  const books = data.books.map(toBookMeta);

  if (searchParams.get('meta') === '1') {
    return NextResponse.json({
      installed: true,
      version: data.version,
      books,
    });
  }

  const quickReference = searchParams.get('ref')?.trim();
  const reference = quickReference
    ? parseReference(quickReference, books)
    : parseDirectReference(searchParams, books);

  if (!reference) {
    return NextResponse.json(
      {
        error: 'invalid_reference',
        message: '성경 참조를 인식하지 못했습니다. 예: 요3:16-18, 창1:1-5, 롬8:28,31-39',
      },
      { status: 400 }
    );
  }

  const verses = getChapterVerses(data, reference);
  if (verses.length === 0) {
    return NextResponse.json(
      {
        error: 'reference_not_found',
        message: '요청한 장절을 로컬 성경 본문에서 찾지 못했습니다.',
        reference: formatReference(reference),
      },
      { status: 404 }
    );
  }

  const versesPerSection = clampVersesPerSection(searchParams.get('versesPerSection'));

  return NextResponse.json({
    installed: true,
    version: data.version,
    reference: formatReference(reference),
    bookId: reference.bookId,
    chapter: reference.chapter,
    verses,
    versesPerSection,
    sections: buildSections(verses, versesPerSection),
  });
}
